server:
  port: 9631
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hu690931351/aishop.git
          username: 690931351@qq.com
          password: hu147258..
